server:
  port: 8081

# 服务名称
spring:
  application:
    name: hb-realtime-computation-service
  profiles:
    active: @product.env@
    main:
      allow-bean-definition-overriding: true
  sleuth:
    sampler:
      probability: 0.3 #抽样比例 默认0.1
  zipkin:
    sender:
      type: kafka
    kafka:
      topic: botech_zipkin
  kafka:
      bootstrap-servers: 192.168.3.244:9092
  redis:
    lettuce:
      pool:
        max-wait: 800ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 50 #连接池最大连接数（使用负值表示没有限制）
        min-idle: 3 #连接池中的最小空闲连接
        max-idle: 50 #连接池中的最大空闲连接
    timeout: 3000ms #连接或读取超时时长（毫秒）
    host: 127.0.0.1
    port: 6379
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache/ehcache.xml
    datasource:
      username: brc
      password: brc
      url: jdbc:oracle:thin:@192.168.3.132:1521/renxiang
      driver-class-name: oracle.jdbc.OracleDriver

# MP配置
mybatis-plus:
  mapper-locations: classpath*:/mapper*/*Mapper.xml
  type-aliases-package: com.botech.rc.**.entity
  configuration:
    lazy-loading-enabled: true
    use-column-label: true
    multiple-result-sets-enabled: true
    map-underscore-to-camel-case: true
    default-executor-type: reuse
    default-statement-timeout: 25000

# eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}:${server.port}
    appname: ${spring.application.name}

# actuator相关配置 用于找到hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
          strategy: SEMAPHORE
      circuitBreaker:
        sleepWindowInMilliseconds: 10s #短路多久以后开始尝试是否恢复，默认5s

# feign配置
feign:
  hystrix:
    enabled: true

# 日志配置
logging:
  config: classpath:config/logback/logback-spring.xml